# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :build do
    build_number = number_of_commits(all: false)

    increment_build_number(
      build_number: build_number
    )

    # sync_code_signing
    build_app
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    
  end

end
