name: ios workflow
on: 
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-11
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter doctor -v

      # Checkout code and prepare the project.
      - name: Checkout code and prepare the project.
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: flutter pub get
      - run: flutter test
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: flutter build ios --release --no-codesign

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.3'
          bundler-cache: true
          working-directory: ios
      
      # Build and deploy with Fastlane 🚀.
      - run: bundle exec fastlane build
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        working-directory: ios

      # - name: Upload artifact to Github
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/flutter-apk/app-release.apk