name: web workflow
on: 
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter doctor -v

      # Checkout code and get packages.
      - name: Checkout code and get packages
        uses: actions/checkout@v2
      - run: flutter pub get
      - run: flutter build web